# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'csci-hw9' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YoutubeHistoryScrapperApp
  pod 'Alamofire', '~> 4.9.1'
  pod 'SwiftyJSON', '~> 4.0.0'
  pod 'Toast-Swift'
  pod 'SwiftSpinner'
  pod 'Charts'
  pod 'XLPagerTabStrip'
  pod 'Alamofire-SwiftyJSON', '~> 3.0.0'

end
